#################################
#           Animaciones         #
#################################

# Habilitar animaciones para ventanas y superficies (docks/statusbars)
animations=1
layer_animations=1

# Animaciones al abrir y cerrar
# Disponible:
# - slide: se desliza la ventana hacia/fuera de la pantalla
# - zoom: la ventana se engrandece/encoge hasta tomar su posición
# - fade: la ventana se esclarece/disipa en la pantalla
# - none: ninguna
animation_type_open=fade
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide

#################################
#          Duraciones           #
#           (en ms)             #
#################################

# Duración de la animación de movimiento
animation_duration_move=500

# Duración de la animación al generar una nueva ventana
animation_duration_open=400

# Duración de las animaciones de los tags
animation_duration_tag=300

# Duración de la animación al cerrar una ventana
animation_duration_close=300

# Duración de la animación al cambiar enfoque
# - (aplica cuando tienen diferentes valores de opacidad)
animation_duration_focus=0

#################################
#             Fade              #
#################################

# Animación fade: esclarecer ventanas entrantes
animation_fade_in=1

# Animación fade: disipar ventanas salientes
animation_fade_out=1

# Opacidad inicial para las animaciones entrantes
fadein_begin_opacity=0.5

# Opacidad inicial para las animaciones salientes
fadeout_begin_opacity=0.5

#################################
#             Zoom              #
#################################

# Animación zoom: nivel inicial
zoom_initial_ratio=0.4

# Animación zoom: nivel final
zoom_end_ratio=0.8

#################################
#       Curvas de Bézier        #
#################################

# - Avanzado, determinan cómo se "siente" una animación
# - Formato x1,y1,x2,y2
# - Puedes visualizar y generar curvas en:
#   - www.cssportal.com/css-cubic-bezier-generator
#   - easings.net

# Curva de animación de abrir
animation_curve_open=0.46,1.0,0.29,1

# Curva de animación de mover
animation_curve_move=0.46,1.0,0.29,1

# Curva de animaciones de tags
animation_curve_tag=0.46,1.0,0.29,1

# Curva de animación de cerrar
animation_curve_close=0.08,0.92,0,1

# Curva de animaciones de enfoque
animation_curve_focus=0.46,1.0,0.29,1

# Curva de opacidad de animación de abrir
animation_curve_opafadein=0.46,1.0,0.29,1

# Curva de opacidad de animación de cerrar
animation_curve_opafadeout=0.5,0.5,0.5,0.5

#### Dirección de animación de cambio de tag ####
# - 0: vertical (útil para hacer un setup scroller tipo niri)
# - 1: horizontal (predeterminado)
tag_animation_direction=1

