#################################
#      Programas de inicio      #
#################################

# Inicio simple
# (comenzar sólo la primera vez que inicie mangowm)
exec-once=waybar
exec-once=dunst
exec-once=pipewire
exec-once=pipewire-pulse
exec-once=wireplumber
exec-once=ydotoold

# Inicio repetido
# (comenzar cada vez que se refresque el archivo de config)
exec=xrdb $XRESOURCES
exec=~/.local/bin/wallpaper

