# Todas las opciones disponibles en https://mangowm.github.io/docs/

#### Inputs ####
source=./inputs.conf

#### Keybindings ####
source=./binds.conf

#### Reglas de comportamiento ####
source=./rules.conf

#### Layouts ####
source=./layouts.conf

#### Apariencia ####
source=./theme.conf

#### Efectos de ventanas ####
source=./effects.conf

### Animaciones ###
source=./animations.conf

#### Scratchpads ####
source=./scratchpads.conf

#### Programas de inicio ####
source=./autostart.conf

