#################################
#     Efectos de apariencia     #
#    (análogo a picom de X11)   #
#################################

#################################
#             Blur              #
#################################

# Habilitar efecto de blur
# - (el efecto blur tiene un gran impacto sobre el desempeño,
# se recomienda siempre optimizarlo o bien deshabilitarlo)
blur=1

# Habilitar blur para superficies como 
# docks y statusbars
blur_layer=0

# Optimizar blur (muy recomendado)
# 0: No optimizado, la transparencia/blur se generan en tiempo real
# 1: Optimizado, la transparencia/blur se generan respecto del fondo de pantalla
blur_optimized=0

# Radio (intensidad) del blur
blur_params_radius = 9

# Iteraciones (calidad) del blur
blur_params_num_passes = 2

# Ruido en el blur
blur_params_noise = 0.02

# Brillo del blur
blur_params_brightness = 0.9

# Contraste del blur
blur_params_contrast = 0.9

# Saturación del blur
blur_params_saturation = 1.2

#################################
#           Sombras             #
#################################

# Habilitar sombras bajo ventanas
shadows = 1

# Habilitar sombras bajo superficies (docks/statusbars)
layer_shadows = 0

# Habilitar sombras sólo para ventanas flotantes
# - (ayuda con el desempeño del hardware)
shadow_only_floating = 0

# Tamaño de las sombras
shadows_size = 10

# Blur de las sombras
shadows_blur = 15

# Posición de las sombras
shadows_position_x = 0
shadows_position_y = 0

# Color de las sombras
shadowscolor= 0x000000ff

#################################
#           Esquinas            #
#################################

# Radio de las esquinas de las ventanas
border_radius=10

# Habilitar esquinas redondas para las 4 esquinas
border_radius_location_default=0

# Deshabilitar esquinas redondas cuando sólo hay una ventana
no_radius_when_single=0

#################################
#           Opacidad            #
#################################

# Opacidad de la ventana enfocada
focused_opacity=1.0

# Opacidad de las ventanas desenfocadas
unfocused_opacity=1.0

