#################################
#             Inputs            #
#  (teclado, mouse y trackpad)  #
#################################

#### Teclado ####

# Establecer layout de teclado
xkb_rules_layout=latam,us

# Configuraciones personales de teclado
# - Alternar CapsLock con ESC
# - Reemplazar PrtSc con una segunda tecla SUPER
xkb_rules_options=caps:swapescape,altwin:prtsc_rwin

# Reducir el tiempo de espera entre repetición de teclas y aumentar
# velocidad de repetición
repeat_delay=300
repeat_rate=50

# Comenzar con NumLock habilitado
#numlockon=1

#### Mouse/Trackpoint ####

# Ajuste de velocidad de mouse (-1.0 a 1.0)
mouse_accel_speed=0.7

# Scroll natural (invertir dirección de scroll)
#mouse_natural_scrolling=1

# Perfil de aceleración del mouse
# - 0: Apagada
# - 1: Constante
# - 2: Adaptativa (predeterminada)
#mouse_accel_profile=2


#### Trackpad ####

# Deshabilitar trackpad
#disable_trackpad=0

# Ajuste de velocidad de trackpad (-1.0 a 1.0)
#trackpad_accel_speed=0

# Scroll natural con el trackpad (habilitado)
# - movimiento de abajo-arriba lleva la página hacia abajo
# - movimiento de arriba-abajo lleva la página hacia arriba
trackpad_natural_scrolling=1

# Deshabilitar trackpad mientras se teclea
disable_while_typing=1
