#################################
#          Scratchpads          #
#################################


# Anchura predeterminada de los scratchpads relativa 
# al tamaño de la pantalla
scratchpad_width_ratio=0.8

# Altura predeterminada de los scratchpads relativa 
# al tamaño de la pantalla
scratchpad_height_ratio=0.9

# Scratchpad de terminal
windowrule=isnamedscratchpad:1,width:1280,height:800,appid:st-scratch
bind=SUPER+ALT,s,toggle_named_scratchpad,st-scratch,none,st -c st-scratch

# Match by title
windowrule=isnamedscratchpad:1,width:1000,height:700,title:kitty-scratch

