#################################
#          Apariencia           #
#################################

#################################
#            Cursor             #
#################################

# Tamaño
cursor_size=24

# Tipo
cursor_theme=Adwaita

#################################
#          Dimensiones          #
#################################

# Grosor de los bordes
borderpx=2

# Espaciado horizontal entre ventanas
gappih=10

# Espaciado vertical entre ventanas
gappiv=10

# Espaciado horizontal externo
gappoh=10

# Espaciado vertical externo
gappov=10

#################################
#           Ventanas            #
#################################

# Color de fondo de la ventana principal
# - #201b14
rootcolor=0x201b14ff

# Color del borde de las ventanas inactivas
# - #333333
bordercolor=0x333333ff

# Color del borde de la ventana activa
# - #f7b83d
focuscolor=0xf7b83dff

# Color del borde de las ventanas globales/sticky
# - #B153A7
globalcolor=0xb153a7ff

# Color del borde de las ventanas urgentes
# - #ad401f
urgentcolor=0xad401fff

# Color del borde de las ventanas resaltadas
# - #14a57c
overlaycolor=0x14a57cff

# Color de las sombras que se demuestran al arrastrar ventanas
# - #8FBA7C
dropcolor=0x8FBA7C55

# Color del borde de las ventanas en dwindle manual
# - #EB441E
splitcolor=0xEB441EFF

# Color del borde de las ventanas maximizadas
# - #89aa61
maximizescreencolor=0x89aa61ff

# Color del borde de las ventanas scratchpad
# - #f7b83d 
scratchpadcolor=0xf7b83dff



#################################
#        Monocle Tab Bar        #
#################################

## Altura
tab_bar_height=50

# Color de texto: #f7b83d
tab_bar_decorate_fg_color=0xf7b83dff

# Color de fondo: #222222
tab_bar_decorate_bg_color=0x222222ff

# Color de texto enfocado: #222222
tab_bar_decorate_focus_fg_color=0x222222ff

# Color de fondo enfocado: #f7b83d
tab_bar_decorate_focus_bg_color=0xf7b83dff

# Color del borde: #8BAA9B
tab_bar_decorate_border_color=0x201b14ff

# Grosor del borde
tab_bar_decorate_border_width=4

# Radio de las esquinas del borde
tab_bar_decorate_corner_radius=5

# Espaciado horizontal
tab_bar_decorate_padding_x=0

# Espaciado vertical
tab_bar_decorate_padding_y=0

# Fuente
tab_bar_decorate_font_desc=monospace Bold 16

