#!/bin/sh
if [ -n "$FIFO_UEBERZUG" ]; then
	printf '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"
	#kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty
fi
