#!/bin/sh
# Based heavily on https://github.com/cirala/lfimg and https://github.com/cirala/lfimg/blob/master/preview
case "$1" in 
	*rsa*|*ssh*|*gpg*) exit;;
esac

ft=$( file --mime-type "$1" -b )

#echo "$ft"
#exit

#case "$1" in
#    *.tar*) tar tf "$1";;
#    *.zip) unzip -l "$1";;
#    *.rar) unrar-free l "$1";;
#    #*.7z) 7z l "$1";;
#    *.pdf) pdftotext "$1" -;;
#    *.jpg | *.png) exiftool "$1" ;;
#    *) highlight -O ansi "$1";;
#esac

#echo "$1"
#echo "$2"
#echo "$3"
#echo "$4"

ubpreview()
{
	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
		exit 1
	else
		exiftool "$1"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
#CACHE="/tmp/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

#echo $CACHE

case "$ft" in
	image/*) ubpreview "$1" "$2" "$3" "$4" "$5" ;;
	#application/pdf) pdftotext "$1" - ;;
	application/pdf)
		[ ! -f "${CACHE}.jpg" ] && \
			pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		ubpreview "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;

	application/epub*)
		[ ! -f "$CACHE" ] && \
			epub-thumbnailer "$1" "$CACHE" 1024
		ubpreview "$CACHE" "$2" "$3" "$4" "$5"
		;;
	video/*) 
		[ ! -f "${CACHE}.jpg" ] && \
			ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		ubpreview "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
	application/x-rar) unrar-free l "$1";;
	#text/*) highlight -O ansi "$1";;
	text/*) bat --wrap character --terminal-width "$(($4 - 6))" -f "$1" ;;
	#text/*) bat "$1" ;;
	*/zstd | */gzip) tar tf "$1";;
    	application/zip) unzip -l "$1";;
esac

